name: Package and release templates

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Zip templates
        run: |
          mkdir dist
          zip -r "dist/vanila-${VERSION}.zip" vanila
#          zip -r "dist/react-${VERSION}.zip" react
#          zip -r "dist/svelte-${VERSION}.zip" svelte

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/vanila-${{ env.VERSION }}.zip
#            dist/react-${{ env.VERSION }}.zip
#            dist/svelte-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CICD }}
